version: "3"

services:
  tgpt:
    container_name: tgpt
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5050:5050
    env_file: "local.env"

  qdrant:
    container_name: tgpt-qdrant
    image: qdrant/qdrant:latest
    restart: always
    volumes:
      - ./qdrant_data:/qdrant/storage

  ollama:
    container_name: tgpt-ollama
    image: ollama/ollama:latest
    restart: always
